"""Opis zmiany, np. Dodano relację grupową

Revision ID: 15df6bd83885
Revises: 2837dcb910da
Create Date: 2025-08-04 23:33:52.748791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15df6bd83885'
down_revision = '2837dcb910da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
