"""Dodano break_minutes do Presence

Revision ID: 2537fd75f7c2
Revises: f22b1191ba1a
Create Date: 2025-08-04 23:59:53.446979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2537fd75f7c2'
down_revision = 'f22b1191ba1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
