"""Dodano break_minutes do Presence

Revision ID: 2837dcb910da
Revises: 4c2d391cd3f0
Create Date: 2025-08-04 19:54:07.522170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2837dcb910da'
down_revision = '4c2d391cd3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
