"""Dodano break_minutes do Presence

Revision ID: 321e37726eee
Revises: 2537fd75f7c2
Create Date: 2025-08-05 00:04:49.639498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321e37726eee'
down_revision = '2537fd75f7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
