"""Dodano break_minutes do Presence

Revision ID: 4c2d391cd3f0
Revises: 28e26ebc8473
Create Date: 2025-08-04 19:50:03.998533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2d391cd3f0'
down_revision = '28e26ebc8473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
