"""Dodano break_minutes do Presence

Revision ID: 5abe411c9b3b
Revises: 321e37726eee
Create Date: 2025-08-05 00:12:04.018896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abe411c9b3b'
down_revision = '321e37726eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
