"""Dodano break_minutes do Presence

Revision ID: 81161ebd2f6d
Revises: 15df6bd83885
Create Date: 2025-08-04 23:41:39.802773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81161ebd2f6d'
down_revision = '15df6bd83885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
