"""add break_minutes to Presence

Revision ID: 8af54f578681
Revises: 
Create Date: 2025-08-01 18:08:50.088581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af54f578681'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_settings')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('external_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('piece_rate')

    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('break_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.drop_column('break_minutes')

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piece_rate', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('external_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    op.create_table('daily_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('field_id', sa.INTEGER(), nullable=False),
    sa.Column('variety_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['berry_variety.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # ### end Alembic commands ###
