"""Dodaj pole piece_rate do Entry

Revision ID: c612be4f7832
Revises: 8af54f578681
Create Date: 2025-08-01 22:15:40.559650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c612be4f7832'
down_revision = '8af54f578681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piece_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('piece_rate')

    # ### end Alembic commands ###
