"""Dodano break_minutes do Presence

Revision ID: f22b1191ba1a
Revises: 81161ebd2f6d
Create Date: 2025-08-04 23:49:49.299082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22b1191ba1a'
down_revision = '81161ebd2f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
